"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, BadgeCheck, Ban, Building2, Copy, KeyRound, Plus, ShieldCheck, Users } from "lucide-react";

type License = { id:string; code_hint:string; customer_name:string; customer_email:string|null; license_type:string; plan:string; status:string; user_limit:number; expires_at:string|null; activated_at:string|null; created_at:string };

export default function AdminLicenses({ initialLicenses }:{ initialLicenses:License[] }) {
  const [licenses,setLicenses]=useState(initialLicenses); const [message,setMessage]=useState(""); const [code,setCode]=useState(""); const [busy,setBusy]=useState(false);
  async function create(fd:FormData){setBusy(true);setMessage("");setCode("");const r=await fetch("/api/admin/licenses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(fd))});const j=await r.json() as {error?:string;code?:string};setBusy(false);if(!r.ok){setMessage(j.error||"No se pudo emitir la licencia.");return;}setCode(j.code||"");setMessage("Licencia emitida. Copiá el código ahora: luego solo se mostrará su terminación. Recargá la página después de copiarlo.");}
  async function change(id:string,status:string){const r=await fetch("/api/admin/licenses",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});if(r.ok)setLicenses(v=>v.map(x=>x.id===id?{...x,status}:x));else setMessage("No se pudo actualizar la licencia.");}
  return <main className="admin-page"><header className="admin-header"><div><span><ShieldCheck/> GIAN CONTROL</span><h1>Licencias comerciales</h1><p>Autorizá, suspendé y controlá quién utiliza la aplicación.</p></div><Link href="/"><ArrowLeft/>Volver a la app</Link></header>
    <section className="admin-stats"><article><BadgeCheck/><div><strong>{licenses.filter(x=>x.status==="active").length}</strong><span>Activas</span></div></article><article><KeyRound/><div><strong>{licenses.filter(x=>x.status==="pending").length}</strong><span>Pendientes</span></div></article><article><Users/><div><strong>{licenses.length}</strong><span>Total emitidas</span></div></article></section>
    <section className="admin-grid"><form action={create} className="admin-card"><h2><Plus/>Emitir licencia</h2><label>Abogado o estudio<input name="customerName" required placeholder="Estudio Jurídico Pérez"/></label><label>Correo autorizado<input name="customerEmail" type="email" placeholder="abogado@estudio.com"/></label><div className="admin-row"><label>Plan<select name="plan" defaultValue="individual"><option value="individual">Individual</option><option value="estudio">Estudio</option><option value="demo">Demostración</option></select></label><label>Cupo<input name="userLimit" type="number" min="1" max="50" defaultValue="1"/></label></div><label>Vencimiento<input name="expiresAt" type="datetime-local"/></label><button disabled={busy}><Plus/>{busy?"Emitiendo…":"Crear código"}</button>{message&&<p className="admin-message">{message}</p>}{code&&<div className="license-code"><strong>{code}</strong><button type="button" onClick={()=>navigator.clipboard.writeText(code)}><Copy/>Copiar</button></div>}</form>
      <section className="admin-card admin-list"><h2><Building2/>Clientes y licencias</h2>{licenses.length===0?<p className="empty">Todavía no hay licencias emitidas.</p>:licenses.map(l=><article key={l.id}><div><strong>{l.customer_name}</strong><span>{l.customer_email||"Sin correo limitado"} · {l.code_hint} · Plan {l.plan}</span></div><b className={`license-status ${l.status}`}>{l.status}</b><div className="license-actions">{l.license_type==="platform_admin"?<span>Administración principal</span>:l.status==="active"?<button onClick={()=>change(l.id,"suspended")}><Ban/>Suspender</button>:l.status==="suspended"?<button onClick={()=>change(l.id,"active")}><BadgeCheck/>Reactivar</button>:<span>Esperando activación</span>}</div></article>)}</section>
    </section></main>;
}
