"use client";
import {useState} from "react";
import {CalendarDays,CheckCircle2,Clock3,Loader2,Send} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";

export default function RequestForm({bookingCode}:{bookingCode:string}){
  const [state,setState]=useState<"idle"|"sending"|"done">("idle"),[error,setError]=useState("");
  async function submit(fd:FormData){setState("sending");setError("");const body={...Object.fromEntries(fd),bookingCode,consent:fd.get("consent")==="on"};try{const r=await fetch("/api/prospects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json() as {error?:string};if(!r.ok)throw Error(j.error||"No pudimos enviar la solicitud.");setState("done")}catch(e){setError(e instanceof Error?e.message:"No pudimos enviar la solicitud.");setState("idle")}}
  if(state==="done")return <div className="request-success rounded-2xl border border-emerald-200 bg-white p-8 text-center shadow-sm"><CheckCircle2 className="mx-auto size-14 text-emerald-600"/><h3 className="mt-4 text-2xl font-bold">Solicitud recibida</h3><strong>Pendiente de confirmación</strong><p className="mx-auto mt-2 max-w-md leading-7 text-[#607184]">Tus datos y tu disponibilidad quedaron registrados. La entrevista todavía no está confirmada: aguardá el mensaje o la llamada del estudio para acordar el día y el horario definitivos.</p><Button className="mt-6" onClick={()=>setState("idle")}>Enviar otra solicitud</Button></div>;
  return <form action={submit} className="grid gap-5 rounded-2xl border bg-white p-5 shadow-sm sm:grid-cols-2 sm:p-8"><input name="website" className="hidden" tabIndex={-1} autoComplete="off"/><Field label="Nombre" name="firstName" required/><Field label="Apellido" name="lastName" required/><Field label="DNI (opcional)" name="document" inputMode="numeric"/><Field label="Celular con característica" name="phone" required inputMode="tel" placeholder="Ej.: 3878 506500"/><Field label="Correo electrónico (opcional)" name="email" type="email"/><label className="grid gap-2 text-sm font-semibold">Canal preferido<select name="preferredChannel" className="h-10 rounded-md border bg-white px-3 text-base"><option>WhatsApp</option><option>Llamada telefónica</option><option>Correo electrónico</option></select></label><label className="grid gap-2 text-sm font-semibold">Modalidad preferida<select name="interviewMode" className="h-10 rounded-md border bg-white px-3 text-base"><option>Presencial</option><option>Virtual</option><option>Indistinta</option></select></label><label className="grid gap-2 text-sm font-semibold">Urgencia<select name="urgency" className="h-10 rounded-md border bg-white px-3 text-base"><option>Normal</option><option>Próximos días</option><option>Urgente - tengo un vencimiento</option></select></label><label className="date-field"><span><CalendarDays/>Fecha probable</span><Input name="preferredDate" type="date" required min={new Date().toISOString().slice(0,10)}/></label><label className="date-field"><span><Clock3/>Horario probable</span><Input name="preferredHour" type="time" required/></label><label className="grid gap-2 text-sm font-semibold sm:col-span-2">Otra disponibilidad u observación<Input name="preferredTime" placeholder="Ej.: también puedo asistir los miércoles por la tarde"/></label><label className="grid gap-2 text-sm font-semibold sm:col-span-2">Motivo de la entrevista<textarea name="reason" required minLength={10} maxLength={1200} rows={5} className="rounded-md border p-3 text-base font-normal outline-none" placeholder="Describí brevemente el tema. Evitá incluir contraseñas o información innecesaria."/></label><label className="flex items-start gap-3 text-sm leading-6 text-[#526576] sm:col-span-2"><input name="consent" type="checkbox" required className="mt-1 size-4 accent-[#4f46e5]"/><span>Autorizo al estudio a utilizar estos datos únicamente para analizar y gestionar mi solicitud de entrevista.</span></label>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-700 sm:col-span-2">{error}</p>}<div className="sm:col-span-2"><Button disabled={state==="sending"} size="lg" className="w-full sm:w-auto">{state==="sending"?<Loader2 className="animate-spin"/>:<Send/>}{state==="sending"?"Enviando…":"Enviar solicitud"}</Button></div></form>
}
function Field({label,name,...rest}:{label:string;name:string;[key:string]:unknown}){return <label className="grid gap-2 text-sm font-semibold">{label}<Input name={name} {...rest}/></label>}
