-- Control comercial GIAN: organizaciones, miembros y licencias de un solo uso.
create table if not exists public.organizations(id uuid primary key default gen_random_uuid(),name text not null,status text not null default 'active' check(status in('active','suspended','cancelled')),plan text not null default 'individual' check(plan in('individual','estudio','demo')),user_limit integer not null default 1 check(user_limit>0),license_expires_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.organization_members(organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null default 'owner' check(role in('owner','lawyer','assistant','viewer')),status text not null default 'active' check(status in('active','suspended')),created_at timestamptz not null default now(),primary key(organization_id,user_id));
create table if not exists public.platform_admins(user_id uuid primary key references auth.users(id) on delete cascade,created_at timestamptz not null default now());
create table if not exists public.licenses(id uuid primary key default gen_random_uuid(),code_hash text not null unique,code_hint text not null,customer_name text not null,customer_email text,license_type text not null default 'customer' check(license_type in('customer','platform_admin')),plan text not null default 'individual' check(plan in('individual','estudio','demo')),status text not null default 'pending' check(status in('pending','active','suspended','expired','cancelled')),user_limit integer not null default 1 check(user_limit>0),expires_at timestamptz,organization_id uuid references public.organizations(id),activated_by uuid references auth.users(id),activated_at timestamptz,created_by uuid references auth.users(id),created_at timestamptz not null default now());
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.platform_admins enable row level security;
alter table public.licenses enable row level security;

create or replace function public.is_platform_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.platform_admins where user_id=(select auth.uid()))$$;
revoke all on function public.is_platform_admin() from public,anon; grant execute on function public.is_platform_admin() to authenticated;
create policy "organizations member read" on public.organizations for select to authenticated using(public.is_platform_admin() or exists(select 1 from public.organization_members m where m.organization_id=organizations.id and m.user_id=(select auth.uid()) and m.status='active'));
create policy "organizations admin update" on public.organizations for update to authenticated using(public.is_platform_admin()) with check(public.is_platform_admin());
create policy "members own or admin read" on public.organization_members for select to authenticated using(user_id=(select auth.uid()) or public.is_platform_admin());
create policy "members admin manage" on public.organization_members for all to authenticated using(public.is_platform_admin()) with check(public.is_platform_admin());
create policy "platform admin own read" on public.platform_admins for select to authenticated using(user_id=(select auth.uid()));
create policy "licenses admin or activated read" on public.licenses for select to authenticated using(public.is_platform_admin() or activated_by=(select auth.uid()));
create policy "licenses admin insert" on public.licenses for insert to authenticated with check(public.is_platform_admin() and created_by=(select auth.uid()));
create policy "licenses admin update" on public.licenses for update to authenticated using(public.is_platform_admin()) with check(public.is_platform_admin());

create or replace function public.license_available(p_code_hash text,p_email text) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.licenses l where l.code_hash=p_code_hash and l.status='pending' and (l.customer_email is null or lower(l.customer_email)=lower(trim(p_email))) and (l.expires_at is null or l.expires_at>now()))$$;
revoke all on function public.license_available(text,text) from public,authenticated; grant execute on function public.license_available(text,text) to anon;
create or replace function public.claim_license(p_code_hash text) returns jsonb language plpgsql security definer set search_path='' as $$declare v_license public.licenses%rowtype;v_org uuid;v_uid uuid;v_email text;v_name text;begin v_uid:=(select auth.uid());if v_uid is null then raise exception 'Debés iniciar sesión para activar la licencia.';end if;select lower(email),coalesce(raw_user_meta_data->>'full_name','') into v_email,v_name from auth.users where id=v_uid;select * into v_license from public.licenses where code_hash=p_code_hash for update;if not found or v_license.status<>'pending' then raise exception 'Código inválido o ya utilizado.';end if;if v_license.customer_email is not null and lower(v_license.customer_email)<>v_email then raise exception 'Este código corresponde a otro correo.';end if;if v_license.expires_at is not null and v_license.expires_at<=now() then update public.licenses set status='expired' where id=v_license.id;raise exception 'El código venció.';end if;insert into public.organizations(name,plan,user_limit,license_expires_at) values(coalesce(nullif(trim(v_license.customer_name),''),nullif(trim(v_name),''),'Estudio jurídico'),v_license.plan,v_license.user_limit,v_license.expires_at) returning id into v_org;insert into public.organization_members(organization_id,user_id,role) values(v_org,v_uid,'owner');if v_license.license_type='platform_admin' then insert into public.platform_admins(user_id) values(v_uid) on conflict do nothing;end if;update public.licenses set status='active',organization_id=v_org,activated_by=v_uid,activated_at=now() where id=v_license.id;return jsonb_build_object('ok',true,'organization_id',v_org,'is_platform_admin',v_license.license_type='platform_admin');end$$;
revoke all on function public.claim_license(text) from public,anon; grant execute on function public.claim_license(text) to authenticated;
create or replace function public.account_access_status() returns jsonb language sql stable security definer set search_path='' as $$select coalesce((select jsonb_build_object('authorized',o.status='active' and (o.license_expires_at is null or o.license_expires_at>now()) and m.status='active','organization_id',o.id,'organization_name',o.name,'plan',o.plan,'expires_at',o.license_expires_at,'role',m.role,'is_platform_admin',public.is_platform_admin()) from public.organization_members m join public.organizations o on o.id=m.organization_id where m.user_id=(select auth.uid()) order by m.created_at limit 1),jsonb_build_object('authorized',false,'is_platform_admin',public.is_platform_admin()))$$;
revoke all on function public.account_access_status() from public,anon; grant execute on function public.account_access_status() to authenticated;
insert into public.licenses(code_hash,code_hint,customer_name,license_type,plan,user_limit,status) values('7a9010ef7ed2e2c0c43946586371413044b00e9e424407f9553066e1643455d7','••••2e01','GIAN Producciones Inteligentes','platform_admin','estudio',10,'pending') on conflict(code_hash) do nothing;
create index if not exists organization_members_user_idx on public.organization_members(user_id);
create index if not exists licenses_status_idx on public.licenses(status,created_at desc);
